name: ghostcloud
version: 0.9.0
grade: stable
confinement: strict
base: core18
summary: A modern cross-platform client for Nextcloud, ownCloud, WebDav.
description: |
  Allows you to easily access your NextCloud, ownCloud and WebDav 
  instances with a cross-platform, native Free Software application.

apps:
  ghostcloud:
    environment:
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/qt5/plugins
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/qt5/qml
    command: desktop-launch harbour-owncloud
    plugs: [ x11, wayland, desktop, opengl, pulseaudio, home, removable-media ]
    desktop: usr/share/applications/harbour-owncloud.desktop

parts:
  harbour-owncloud:
    plugin: qmake
    source: .
    options:
      - CONFIG+=noadditionals
      - CONFIG+=quickcontrols
    project-files:
      - harbour-owncloud.pro
    build-packages:
      - make
      - build-essential
      - qt5-qmake
      - qttools5-dev
      - build-essential
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - libqt5xmlpatterns5-dev
      - qtmultimedia5-dev
      - libqt5webkit5-dev
      - qtbase5-dev
      - libevdev-dev
      - libudev-dev
      - qml-module-qtquick2
      - qml-module-qtgraphicaleffects
      - qml-module-qtquick-window2
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-extras
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qtquick-controls
      - qml-module-qt-labs-settings
      - qml-module-qtquick-localstorage
    stage:
      - usr/bin/*
      - usr/lib/*
      - usr/share/*
    prime:
      - usr/bin/harbour-owncloud
      - usr/lib/*
      - usr/share/*
    stage-packages:
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
    after: [ desktop-qt5 ]
  desktop-qt5:
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
