name: qhostcloud
version: 0.9.0
grade: stable
confinement: strict
base: core18
summary: A modern cross-platform client for Nextcloud, ownCloud, WebDav.
description: |
  Allows you to easily access your NextCloud, ownCloud and WebDav 
  instances with a cross-platform, native Free Software application.

apps:
  qhostcloud:
    environment:
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml
    command: desktop-launch harbour-owncloud
    plugs: [ x11, wayland, desktop, opengl, pulseaudio, home, removable-media ]
    desktop: usr/share/applications/harbour-owncloud.desktop

parts:
  harbour-owncloud:
    plugin: qmake
    options:
      - CONFIG+=noadditionals
      - CONFIG+=quickcontrols
    qt-version: qt5
    project-files: [ 'harbour-owncloud.pro' ]
    build-packages:
      - make
      - build-essential
      - qt5-qmake
      - qttools5-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - libqt5xmlpatterns5-dev
      - qtmultimedia5-dev
      - qtbase5-dev
      - libevdev-dev
      - libudev-dev
      - qml-module-qtquick2
    stage:
      - usr/bin/*
      - usr/lib/*
      - usr/share/*
    prime:
      - usr/bin/harbour-owncloud
      - usr/lib/*
      - usr/share/*
    after: [ desktop-qt5 ]
  env:
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - libqt5gui5
      - libqt5qml5
      - libqt5quick5
      - libqt5network5
      - libqt5multimedia5
      - libqt5multimediawidgets5
      - libqt5multimedia5-plugins
      - libqt5svg5
      - libqt5xml5
      - libqt5xmlpatterns5
      - libqt5sql5-sqlite
      - libqt5waylandclient5
      - qml-module-qtquick2
      - qml-module-qtgraphicaleffects
      - qml-module-qtquick-window2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-extras
      - qml-module-qtquick-localstorage
      - qtwayland5
    after: [ harbour-owncloud ]
